InventoryManagement/Areas/Transactions/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ServiceLayer.Transactions;
using HotelManagementErp_Main.Helper;
using ViewModel.Transactions;
using System.Net;
using Newtonsoft.Json;
namespace InventoryManagement.Areas.Transactions.Controllers
{

    public class PaymentController : InventoryBaseController
    {
        //
        // GET: /Transactions/Payment/
        PaymentServiceLayer _db;
        
        public ActionResult Index()

        {

            //ViewBag.Tag = Tag;
         
            return View();
        }
        public ActionResult List( string search = "")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo ;
            _db = new PaymentServiceLayer(_dashboardData);
            
            var lst = _db.List(search);
            return View(lst);
        }
        public ActionResult Create(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
             PaymentInfo modelPayment;
            // ViewBag.Tag = Tag;
             //var lst = new ServiceLayer.AccountMaster.CustomerServicesLayer(_dashboardData.DbConnectionString).DDLBind(Tag, "").ToList();
            if (Id != 0)
            {
                modelPayment = _db.Find(Id);

                //  ModelPurMaster.ItemDetails.Add(new Purchase_Tra());

            }
            else
            {
                modelPayment = new PaymentInfo();
                modelPayment.VC_No = _db.GEN_VC_NO();
                modelPayment.Payment_Date = DateTime.Today;
                //modelPayment.Tag_Type = Tag;
            }
           // modelPayment.User_List = lst;
            BindDDL(modelPayment);
            return View(modelPayment);
        }
        [HttpPost]
        public ActionResult Create(PaymentInfo modelPayment)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = modelPayment.Tag_Type;
            if (ModelState.IsValid == true|| ModelState.IsValid==false)
            {
                if (modelPayment.Id != 0)
                {
                    _db.Update(modelPayment);
                }
                else
                {
                    _db.Create(modelPayment);

                }

                var lst = _db.List(modelPayment.Tag_Type);

                return View("List", lst);
            }
            return View(modelPayment);
        }
        public ActionResult GetBalance(int UserId)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            var bal = _db.GetBalance(UserId);
            return Json(bal, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult ViewPayment(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            PaymentInfo modelPayment;


            if (Id != 0)
            {
                modelPayment = _db.Find(Id);
                //modelReceiptNote = new ReceiptNoteInfo();

            }
            else
            {
                modelPayment = new PaymentInfo();
                modelPayment.Payment_Date = DateTime.Now;

              

              //  modelPayment.Receipt_Note_No = _db.GEN_ReceiptNo();

            }

            return PartialView(modelPayment);
        }
        public ActionResult GetChequeDetails(int Id=0,string Cheque_No="")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            var bal = _db.GetChequeDetails(Id,Cheque_No);
            return Json(!bal, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PaymentDetails(int UserId=0,string Tag="")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            var lst = _db.PaymentDetails(UserId, Tag);
            return View(lst);
        }
        public ActionResult BillDetails(int UserId = 0, string Tag = "")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            var lst = _db.BillDetails(UserId, Tag);
            return View(lst);
        }
        public ActionResult PendingBillList(int UserId = 0,int Id=0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            PaymentInfo modelPayment = new PaymentInfo();
            if (UserId > 0)
            {
                modelPayment.BillList = _db.PendingBillList(UserId,Id);
            }
            return View(modelPayment);
            //return Json(lst, JsonRequestBehavior.AllowGet);
        }
        private void BindDDL(PaymentInfo modelPayment)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);


            modelPayment.User_List = _db.DDLBind("Supplier", "");
            modelPayment.LedgerList = _db.DDLBind("ALL", "");
            //modelPayment.Bill_List = _db.PendingBillList(modelPayment.User_Id);
            modelPayment.BillList = new List<BillList>();
           
        }
        }
    }


InventoryManagement/Areas/Transactions/Controllers/PurchaseController.cs
using HotelManagementErp_Main.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.Ledger;
using ServiceLayer.Transactions;
using ViewModel.Transactions;
using ViewModel.Common;
namespace InventoryManagement.Areas.Transactions.Controllers
{
    public class PurchaseController : InventoryBaseController
    {
        //
        // GET: /Transactions/Purchase/
        PurchaseServiceLayer _db;
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult List(String search="")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);
            
            var lst = _db.List(search);
            return View(lst);
        }

        public ActionResult ViewDetails(int Id = 0, string Challan_No = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);
            var lst = _db.ViewDetails(Id, Challan_No);
            return View(lst);
        }
         
        public ActionResult Create(int Id = 0,long Receipt_Note_Id=0 )
        {

            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);
            //''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
            PurchaseMaster ModelPurMaster=new PurchaseMaster ();
            ServiceLayer.InventoryMaster.StockServiceLayer _stockSL = new ServiceLayer.InventoryMaster.StockServiceLayer(_dashboardData);
            ModelPurMaster.purchase_tra.ledger_common = new Ledger_Common();
           Ledger_Common ddl = BindDDL(ModelPurMaster.purchase_tra.ledger_common); 
           //''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
            
            if (Id != 0 && Receipt_Note_Id==0)
            {
                ModelPurMaster = _db.Find(Id);

               // ModelPurMaster. = new ServiceLayer.Common.CommonServiceLayer().DDLBind("Supplier", "");
                //  ModelPurMaster.ItemDetails.Add(new Purchase_Tra());
                //''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                long Challan_No = _db.Find(ModelPurMaster.Id).Id;
                ModelPurMaster.purchase_tra.listpurchase_tra = _db.ItemDetails(Challan_No);
                ModelPurMaster.purchase_tra.Grand_Total = ModelPurMaster.Grand_Total;
                //ModelPurMaster.listTax.Add(new ViewModel.Common.TaxDetails());
                ViewBag.ChalanNo =  ModelPurMaster.purchase_tra.listpurchase_tra.Count>0? ModelPurMaster.purchase_tra.listpurchase_tra[0].Challan_Number :null;
                //'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
            }

            else if (Id == 0 && Receipt_Note_Id!=0)
            {
              //  PurchaseOrderItem PurchaseOrder = (PurchaseOrderItem)TempData["PurchaseOrderDetails"];
                if (Receipt_Note_Id != 0)
                {
                    ModelPurMaster.Is_Refered = true;
                    ModelPurMaster.Refered_Id = Receipt_Note_Id;
                    ModelPurMaster.Refered_Type = "RECEIPTNOTE";
                    PurchaseOrderItem OrderdItem = new ServiceLayer.Transactions.PurchaseServiceLayer(_dashboardData).GetPurchaseOrderItemList(Receipt_Note_Id); ;
                    OrderdItem.listPurchaseOrderItem.ForEach((x) => ModelPurMaster.purchase_tra.listpurchase_tra.Add(new Purchase_Tra {
                        Id = x.Id, 
                        Item_Id = x.ItemId,
                        ItemName = x.ItemName, 
                        Qty = x.Quantity,
                        Rate = x.Rate, 
                        ProductCode = x.ProductCode,
                        SerialNo = x.SerialNo, 
                        Unit_Name = x.UnitName ?? "", Is_Refered = true }));
                  //  PurchaseOrder.listPurchaseOrderItem.ForEach((x) => ModelPurMaster.purchase_tra.listpurchase_tra.Add(new Purchase_Tra { Id = x.Id, Item_Id = x.ItemId, ItemName = "", Qty = x.Quantity, Rate = x.Rate, ProductCode = x.ProductCode, SerialNo = x.SerialNo, Unit_Name = x.UnitName??"", Is_Refered = true }));
                    ModelPurMaster.purchase_tra.Grand_Total = OrderdItem.TotalAMount;
                    //ModelPurMaster.Supplier_Id = PurchaseOrder != null ? PurchaseOrder.SupplierId : ModelPurMaster.Supplier_Id;
                    //ModelPurMaster.orderId = PurchaseOrder != null ? PurchaseOrder.orderId : ModelPurMaster.orderId;
                    ModelPurMaster.Supplier_Id = OrderdItem.SupplierId;
                    ModelPurMaster.orderId = Receipt_Note_Id;
                    ModelPurMaster.Challan_Number = _db.GEN_ChallanNo();
                    ModelPurMaster.Purchase_Date = DateTime.Today;
                }

                
            }

            else
            {



                ModelPurMaster.UnitList = new List<ViewModel.Common.DDLBind>();
                ModelPurMaster.Challan_Number = _db.GEN_ChallanNo();
                ModelPurMaster.Purchase_Date = DateTime.Today;


                ViewBag.ChalanNo = null;
            }
            

            ModelPurMaster.purchase_tra.taxdetails.listTaxDetails.Add(new ViewModel.Common.TaxDetails());

            if (Id > 0)
            {
                ModelPurMaster.purchase_tra.taxdetails.listTaxDetails = _db.GetTaxList(Id); 
            }
                

            
            ModelPurMaster.purchase_tra.taxdetails.Grand_Total = ModelPurMaster.purchase_tra.Grand_Total;
            ModelPurMaster.purchase_tra.Id = ModelPurMaster.Id;
            DDLBind(ModelPurMaster);
            return View(ModelPurMaster);
        }
        [HttpPost]
        public ActionResult Create(PurchaseMaster ModelPurMaster)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);

            if (ModelState.IsValid == true)
            { 
                if (ModelPurMaster.Id != 0)
                {
                    _db.Update(ModelPurMaster);
                }
                else
                {
                    _db.Create(ModelPurMaster);

                }

                var lst = _db.List();

                return RedirectToAction("index");
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            DDLBind(ModelPurMaster);
            return View(ModelPurMaster);
        }

        public ActionResult GetUnitName(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);

            ServiceLayer.InventoryMaster.StockServiceLayer _stockSL = new ServiceLayer.InventoryMaster.StockServiceLayer(_dashboardData);
            ServiceLayer.Masters.UnitsServiceLayer _unitSL = new ServiceLayer.Masters.UnitsServiceLayer(_dashboardData);
            //var stock = _stockSL.Find(Id);
            //var data = _unitSL.DDLBind().SingleOrDefault(x => x.Id == stock.Unit_Id);
            var data = _stockSL.GetUnitAndAmount(Id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSupplier(string searchText = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);

            var data = new ServiceLayer.AccountMaster.CustomerServicesLayer(_dashboardData).DDLBind("SUPPLIER", searchText);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GentChallanOfPurchase(int Id)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);

            var data = _db.Gen_ChallanOfPurchse(Id);

            var lst = _db.List();

            return View("List", lst);
        }
        public ActionResult ItemList(PurchaseMaster modal)
        {
           // modal.ledger_common = new Ledger_Common();
            var _dashboardData = ViewBag.UserLog;
            _db = new PurchaseServiceLayer(_dashboardData);
            ServiceLayer.InventoryMaster.StockServiceLayer _stockSL = new ServiceLayer.InventoryMaster.StockServiceLayer(_dashboardData);
            var ddl = BindDDL(modal.purchase_tra.ledger_common);
            if (modal.Id != 0)
            {
                var Challan_No = _db.Find(modal.Id).Id;
                modal.purchase_tra.listpurchase_tra = _db.ItemDetails(Challan_No);
                modal.purchase_tra.Grand_Total = modal.Grand_Total;
                //ModelPurMaster.listTax.Add(new ViewModel.Common.TaxDetails());
                ViewBag.ChalanNo = modal.purchase_tra.listpurchase_tra[0].Challan_Number;
            }
            else
            {
                PurchaseOrderItem PurchaseOrder = (PurchaseOrderItem)TempData["PurchaseOrderDetails"];
                if (PurchaseOrder != null)
                {

                    PurchaseOrder.listPurchaseOrderItem.ForEach((x) => modal.purchase_tra.listpurchase_tra.Add(new Purchase_Tra { Id = x.Id, Item_Id = x.ItemId, ItemName = ddl.bindDDl.SingleOrDefault(i => i.Id == x.ItemId).Name, Qty = x.Quantity, Rate = x.Rate, ProductCode = x.ProductCode, SerialNo = x.SerialNo }));
                    modal.purchase_tra.Grand_Total = PurchaseOrder.TotalAMount;
                }
                else
                {
                    //  ModelPurMaster.ItemDetails.Add(new Purchase_Tra());
                    ViewBag.ChalanNo = null;
                }
            }
            // BindDDL(ModelPurMaster);
            //ModelPurMaster.ItemList = _stockSL.DDLBind();
            return View(modal.purchase_tra);
        }

InventoryManagement/Areas/Transactions/Views/Payment/BillDetails.cshtml
@model List<ViewModel.Transactions.BillingDetails>

<script>
    $(function () {

       
    });
    function Fn_ChallanDetails(Challan_No) {
  
        $('#Mymmodal1').modal({ backdrop: 'static' });

        $.ajax({
            url: '@Url.Action("ViewDetails", "Purchase", new { area = "Transactions" })',
            dataType: "html",
            data: { Id: 0, Challan_No: Challan_No },
            success: function (data) {
                $('#ItemDetails').html(data);
            }
        });
    }
</script>
@Html.ActionLink("Back", "Index", "Payment", new { Tag =ViewBag.Tag }, new { @class = "fa fa-arrow-circle-left btn btn-danger" })
<table class="table table-striped table-bordered table-hover table-responsive topmrgn5px" id="example">
    <tr>
        <td>
            Bill Date
        </td>
        <td>
            Challan No
        </td>

        <td>Billing Amount</td>
        <td>Tax Amount</td>
        <td>DiscountAmount</td>
        <td>Net Amount</td>

        <td>View</td>
    </tr>
    @if (Model.Count != 0)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    
                    @Html.DisplayFor(x => item.Billing_Date)

                </td>
                <td>
                    @Html.DisplayFor(x => item.Chalan_No)
                </td>


                <td>
                    @Html.DisplayFor(x => item.Billing_Amount)
                </td>

                <td>
                    @Html.DisplayFor(x => item.Tax_Amount)
                </td>

                <td>
                    @Html.DisplayFor(x => item.Discount_Amount)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Amount)
                </td>
                <td>
                    <input type="button" value="View" onclick="Fn_ChallanDetails('@item.Chalan_No');" />
                
                </td>
                <td>
        </tr>
        }

    }
    else
    {
        <tr>
            <td colspan="5">
                No Records found..
            </td>
        </tr>
    }


</table>
<div class="modal fade modal-sm" id="Mymmodal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:lightgray;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><i class="fa fa-check-square-o"></i>&nbsp;Bill Details</h4>
            </div>
            <div class="modal-body" id="ItemDetails">

               
            </div>
            <div class="modal-footer">


                <button type="button" class="btn btn-xs btn-flat btn-default" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

InventoryManagement/Areas/Transactions/Views/Payment/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = ViewBag.layout;
}

@*<script>
    $(function () {
        ApplyFilterOnTable();
    });
</script>*@



<div id="body" class="row">

    <div id="content">
        @{Html.RenderAction("List", "Payment");}
    </div>
</div>



InventoryManagement/Areas/Transactions/Views/Payment/List.cshtml
@model List<ViewModel.Transactions.PaymentInfo>
  @{
  var grid=new WebGrid(Model,canPage:true,canSort:true,rowsPerPage:20,
  selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
  grid.Pager(WebGridPagerModes.All);
  int row = 0;
  }

<div class="panel">

    <div class="panel-heading  bg-margenta">

        <div class="row">

            <div class="col-md-9">
            <span>@ViewBag.Tag &nbsp;&nbsp; Payment List</span>
            </div>

            <div class="col-md-3">
                @Ajax.ActionLink("New", "Create", "Payment", new { area = "Transactions", Tag = ViewBag.Tag, Id = 0 }, new AjaxOptions
                            {
                                LoadingElementId = "Loader",
                                UpdateTargetId = "PageContent",
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                            }, new { @Class = "btn btn-default btn-xs btn-flat hgt", })
               
                <div class="btn-wrp"><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Import <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#">One</a></li><li><a href="#">Two</a></li><li><a href="#">Three</a></li></ul></div><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Export <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'csv', escape: 'false' });">CSV</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'excel', escape: 'false' });">EXCEL</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'doc', escape: 'false' });">DOC</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'pdf', escape: 'false' });">PDF</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'xml', escape: 'false' });">XML</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'sql', escape: 'false' });">SQL Script</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'json', escape: 'false' });">JSON</a></li></ul></div></div>
                <input type="text" placeholder="Search Here" class="hgt" />

            </div>





        </div>

    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-8" id="gridcontent" style="min-height:450px;border:solid silver 1px;">
                @grid.GetHtml(tableStyle:"gTable table table-responsive",
              
             columns: grid.Columns(
             grid.Column("S.No", format:item=>item.WebGrid.Rows.IndexOf(item)+1  ),
                    
                                        grid.Column("Date", format: (item) => item.Payment_Date.ToString("dd-MM-yyyy")),
                                                 grid.Column(columnName: "VC_No", header: "Bill No", format: @<text> <input type="hidden" id="Id" name="Id" value='@item.Id'  />@item.VC_No</text>),
             //grid.Column("Name", "Supplier Name"),
             //grid.Column("Address", "Address"),
             //grid.Column("Contact_No", "Contact No"),
                             //grid.Column("Email_Id", "Email Id"),
             //    grid.Column(columnName: "Amount", header: "Amount", format: @<i class="fa fa-rupee">&nbsp;&nbsp;@item.Amount</i>),
                       grid.Column(columnName: "Amount", header: "Amount", format: @<i class="fa fa-rupee">&nbsp;&nbsp; @item.Amount.ToString("#." + new string('0', 2))</i>),
            
             grid.Column(header: "Action", format: (item) => new HtmlString(

                                          @Ajax.ActionLink(" ", "Create", "Payment", new { area = "Transactions",  Tag = "SUPPLIER",Id = item.Id, }, new AjaxOptions
                          {
                              LoadingElementId="Loader",
                              UpdateTargetId = "PageContent",
                              HttpMethod = "GET",
                              InsertionMode = InsertionMode.Replace,
                          }, new { @Class = "btn btn-default fa fa-pencil", }).ToString() 
                          ))

       //                         @Ajax.ActionLink("Payment Details", "PaymentDetails", "Payment", new { area = "Transactions", UserId = item.Id, Tag = "SUPPLIER" }, new AjaxOptions
       //                         {

       //                             UpdateTargetId = "PageContent",
       //                             HttpMethod = "GET",
       //                             InsertionMode = InsertionMode.Replace,
       //                         }, new { @Class = "btn btn-xs  btn-default pull-left btn-flat", }).ToString()

       //                   ))


       )
      )
            </div>
            <div class="col-md-4" id="ViewPayment">

                @{Html.RenderAction("ViewPayment", "Payment", new { @area = "Transactions", Id = -1 });}


            </div>
        </div>

    </div>

        </div>



<script>

    $('#gridcontent table tbody tr').click(function () {
        debugger;
        var selectedId = $(this).find("input[type='hidden']").val();

       
        $.ajax({
            url: '@Url.Action("ViewPayment", "Payment")',
            data: { 'Id': selectedId },
            type: "get",
            cache: false,
            success: function (savingStatus) {

                $('#ViewPayment').html(savingStatus);

            },
            error: function (xhr, ajaxOptions, thrownError) {

            }
     });
    });
</script>
<style>
    .gTable tr:hover {
        background-color: skyblue;
    }
    /*.gTable tr:nth-child(1) {
        text-align: left;
        
    }*/

    .gTable tr :nth-child(4)
    
     {
        text-align: right;
    }
    .amount {
        text-align: right;
    }
</style>






InventoryManagement/Areas/Transactions/Views/Payment/PaymentDetails.cshtml
@model List<ViewModel.Transactions.PaymentDetails>
@*@Html.ActionLink("Back", "Index", "Payment", new { Tag = ViewBag.Tag }, new { @class = "fa fa-arrow-circle-left btn btn-danger" })*@

<table class="table table-striped table-bordered table-hover table-responsive topmrgn5px" id="example">
    <tr>
        <td>
            Date
        </td>
        <td>
            Mode
        </td>

        <td>Amount</td>
        @*<td>Tax Amt.</td>
        <td>Bal. Amt</td>*@
        @*<td>
            Action
        </td>*@

    </tr>
    @if (Model.Count != 0)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.Payment_Date)

                </td>
                <td>
                    @Html.DisplayFor(x => item.Payment_Type)
                </td>


                <td align="right">
                    @Html.DisplayFor(x => item.Amount)
                </td>
             
                @*<td align="right">
                    @Html.DisplayFor(x => item.Tax_Amount)
                </td>
               
                <td align="right">
                    @Html.DisplayFor(x => item.Balance_Amount)
                </td>*@
               
                @*<td>
                    @Ajax.ActionLink("Edit", "Create", "Payment", new { area = "Transactions", Tag = item.Tag_Type, Id = item.Id }, new AjaxOptions
                            {
                                LoadingElementId = "Loader",
                                UpdateTargetId = "PageContent",
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                            }, new { @Class = "btn btn-xs  btn-default pull-left btn-flat", })


                </td>*@
            </tr>
        }

    }
    else
    {
        <tr>
            <td colspan="5">
                No Records found..
            </td>
        </tr>
    }


</table>

InventoryManagement/Areas/Transactions/Views/Payment/ViewPayment.cshtml
@model ViewModel.Transactions.PaymentInfo
@{


    string src = null;
    if (Model.Image_Path != null)
    {
        src = Model.Image_Path;
    }
    else
    {
        src = "/Themes/img/demo_img.gif";
    }

}

<div>




    <div class="panel panel-danger managepnl">

        <div class="panel-heading" style="background-color: #C4538A;color:white"><span>View Details</span> </div>


        <div class="panel-body">

            <div class="row">
                <div class="col-md-4">
                    <div id="imgTest">
                        <img src="@src" class="img-responsive img-thumbnail mangaeimg" />
                    </div>
                </div>
                <div class="col-md-8">
                    <table class="table table-responsive topmrgn5px">
                        <tr>
                            <td>
                                @Html.Label("Code")

                                @Html.HiddenFor(x => x.Id)

                            </td>
                            <td>

                                <span>@Model.Code</span>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                @Html.Label("Supplier Name")
                            </td>
                            <td>
                                <span>@Model.Name</span>
                            </td>
                        </tr>



                        <tr>
                            <td>
                                @Html.Label("Contact No")
                            </td>
                            <td>
                                <span>@Model.Contact_No</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.Label("Email")
                            </td>
                            <td>
                                <span>@Model.Email</span>
                            </td>
                        </tr>




                    </table>
                </div>
            </div>

            <table class="table table-responsive  topmrgn5px">




                <tr>
                    <td>
                        @Html.Label("Remarks")
                    </td>
                    <td>
                        <span>@Model.Remarks</span>
                    </td>
                </tr>
            </table>

            <hr style="border:solid silver 1px;" />
            <div align="center"><h4><label>Payment Details</label></h4></div>
            @{
                Html.RenderAction("PaymentDetails", "Payment", new { UserId = Model.User_Id, Tag = "Supplier" });
                }
        </div>

    </div>

</div>