InventoryManagement/Areas/Masters/Controllers/LedgerGroupController.cs
using HotelManagementErp_Main.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;
using ViewModel.Common;
using ServiceLayer.Masters;
using ServiceLayer.Reporthelper.CSVHelper;
using System.Text;
using System.IO;
namespace InventoryManagement.Areas.Masters.Controllers
{
    public class LedgerGroupController : InventoryBaseController
    {
        //
        // GET: /Masters/Ledger/
        LedgerGroupServiceLayer _db;
        public ActionResult Index()
        {
            int val = Convert.ToInt32(TempData["SaveStatus"]);
            if (val != null && val != 0)
            {
                ViewBag.SaveStatus = val;
            }
            return View();
        }
        private Stream GenerateStreamFromString(string s)
        {
            MemoryStream stream = new MemoryStream();
            StreamWriter writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }
        public ActionResult List(string search = "")
        {

            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            var lst = _db.List(search);

            return View(lst);

        }
        public ActionResult Create(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            ViewModel.LadgerGroup.LedgerGroup Lggrp;

            if (Id != 0)
            {
                Lggrp = _db.Find(Id);
                Lggrp.Ledger.ListUnder = _db.DDLBind("LEDGERGROUP", "");
            }
            else
            {
                Lggrp = new ViewModel.LadgerGroup.LedgerGroup();
                Lggrp.Ledger.ListUnder = _db.DDLBind("LEDGERGROUP", "");
            }
            return View(Lggrp);
        }
        [HttpPost]
        public ActionResult Create(ViewModel.LadgerGroup.LedgerGroup modelLedggrp)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            if (ModelState.IsValid)
            {
                if (modelLedggrp.Ledger.Id != 0)
                {
                    _db.Update(modelLedggrp);
                    TempData["SaveStatus"] = 2;

                }
                else
                {
                    _db.create(modelLedggrp);
                    TempData["SaveStatus"] = 1;
                }
                //  var lst = _db.List();
                // return View("Index");
                return RedirectToAction("Index");
            }
            else
            {
                modelLedggrp.Ledger.ListUnder = _db.DDLBind("LEDGERGROUP", "");
                return View(modelLedggrp);
            }
        }
        public ActionResult IsNameExists(ViewModel.LadgerGroup.LedgerGroup model)
        {

            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            return Json(!_db.IsNameExists(model.Ledger.Id, model.Ledger.Name), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            bool result = false;
            if (Id > 0)
            {
                result = _db.Delete(Id);
                TempData["SaveStatus"] = 3;
            }
            //  var lst = _db.List();
            // return PartialView("List", lst);
            return RedirectToAction("Index");
        }

        public ActionResult GetLedger(string searchText = "")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new LedgerGroupServiceLayer(_dashboardData);
            var data = _db.DDLBind("LEDGERGROUP", searchText).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

InventoryManagement/Areas/Masters/Views/LedgerGroup/Create.cshtml
    @model ViewModel.LadgerGroup.LedgerGroup


@*<link href="~/Themes/Content/jquery-ui-1.9.0.custom.css" rel="stylesheet" />
<script src="~/Themes/Scripts/jquery-ui-1.9.0.min.js"></script>*@

<script src="~/Themes/Scripts/jquery.validate.js"></script>
<script src="~/Themes/Scripts/jquery.validate.unobtrusive.js"></script>

<script>
    $(function () {
        $("#Ledger_UnderId").customselect();
        //AutoComplete();
    });
    function AutoComplete(id, url) {
        $('#Group').autocomplete({
            source: function (request, response) {
                var autocompleteUrl = '@Url.Action("GetLedger", "LedgerGroup", new { @area = "Masters" })?searchText=' + request.term;
                $.ajax({
                    url: autocompleteUrl,
                    type: 'GET',
                    cache: false,
                    dataType: 'json',
                    success: function (json) {
                        response($.map(json, function (data, id) {
                            //alert(data);
                            return {
                                
                                label: data.Name,
                                Name: data.Name,
                                //Email: data.Email,
                                //Address: data.Address,
                                Id: data.Id,
                            };
                        }));
                    },
                    //error: function (xmlHttpRequest, textStatus, errorThrown) {
                    //  //  console.log('some error occured', textStatus, errorThrown);
                    //}
                });
            },

            minLength: 1,
            select: function (event, ui) {
                $('#Group').val(ui.item.label)
           
                $('#Ledger_UnderId').val(ui.item.Id);
               // GetValuesByCode(ui.item);
                return false;
            }
        });
    }
    
</script>
@using (Ajax.BeginForm("Create", "LedgerGroup", new { area = "Masters" }, new AjaxOptions { UpdateTargetId = "PageContent", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, LoadingElementId = "Loader" }, new { @id = "form1" }))
{
    @Html.ValidationSummary(true)


    
    
    <div>

     <div class="row">
         <div class="col-lg-3">
         </div>
       <div class="col-lg-6">
          <div class="panel panel-danger">

              <div class="panel-heading" style="background-color: #C4538A;color:white"><span>Ledger Group</span> </div>

                    <div class="panel-body">


                        <div class="row">

                            <div class="col-md-12">
                            <div class="editor-label">

                                @Html.Label("Name")<span style="color:red">*</span>
                                @Html.HiddenFor(x => x.Ledger.Id)
                           </div>
                              
                                @Html.TextBoxFor(m => m.Ledger.Name, new { @placeholder = "Name", @class = "form-control", required = true, minlength = "2", maxlength = "50" })
                                @Html.ValidationMessageFor(m => m.Ledger.Name, null, new { @style = "color:red;" })
                            </div>

                            <div class="col-md-12">

                                @Html.Label("Alias Name")
                                @Html.TextBoxFor(m => m.Ledger.Alias_Name, new { @placeholder = "Alias Name", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Ledger.Alias_Name, null, new { @style = "color:red;" })
                            </div>
                            <div class="col-md-12">
                                @Html.Label("Under Group")
                                @Html.DropDownListFor(m => m.Ledger.UnderId, new SelectList(Model.Ledger.ListUnder, "Id", "Name", Model.Ledger.UnderId), "Primary", new {required = true, @class = "custom-select form-control"})
                                
                                @Html.ValidationMessageFor(m =>m.Ledger.UnderId, null, new { @style = "color:red;" })
                                
                            </div>

                            <div class="col-md-12">
                                @Html.Label("Remarks")
                                @Html.TextBoxFor(m => m.Ledger.Remarks, new { @placeholder = "Remarks", @class = "form-control" })

                                @Html.ValidationMessageFor(m => m.Ledger.Remarks, null, new { @style = "color:red;" })
                            </div>

                            <div class="col-md-12 topmrgn5px">

                                <button type="submit" class="btn btn-primary" onclick="fn_ValidateForm('form1');">Save </button>
                                @Html.ActionLink("Cancel", "Index", "LedgerGroup", new { @class = "btn btn-default" })
                                

                            </div>

                        </div>




                    </div>

                </div>
            </div>
         <div class="col-lg-3">
         </div>
        </div>
    </div>
}


InventoryManagement/Areas/Masters/Views/LedgerGroup/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = ViewBag.layout;
}

<script>
    $(document).ready(function () {
        $('#searchText').click(function () {

            var data = $('#SearchText').val();
            if (data != null)
                FilterData(data, '@Url.Action("List", "LedgerGroup", new { area = "Masters" })', '#gridcontent');
        });

    });

    $(document).ready(function () {
        if ('@ViewBag.SaveStatus' == 1)
            toastr.success('Record successfully Saved');

        else if ('@ViewBag.SaveStatus' == 2)
            toastr.success('Record updated successfully');

        else if ('@ViewBag.SaveStatus' == 3)
            toastr.success('Record deleted successfully');

    });
</script>
<div id="body" class="row topmrgn5px">
    <div id="content" class="col-md-12">
        <div class="panel">

            <div class="panel-heading  bg-margenta">
                <div class="row">

                    <div class="col-md-9">
                        <i class="fa fa-list"></i>
                        <span>Ledger Group</span>


                    </div>

                    <div class="col-md-3">
                        @*@Ajax.ActionLink("New", "Create", "LedgerGroup", new { area = "Masters", Id = 0 }, new AjaxOptions
                            {

                               LoadingElementId = "Loader",
                                 UpdateTargetId = "PageContent",
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                            }, new { @Class = "btn btn-default btn-xs btn-flat hgt", })*@


                        <select class="hgt " id="FileType"><option>Tools</option><option>Import</option><option>Export</option></select>
                        <input type="text" placeholder="Search Here" class="" id="SearchText" />
                        <button class="btn btn-default btn-xs btn-flat hgt fa fa-search" id="searchText" type="button"></button>
                        <button class="btn btn-default btn-xs btn-flat hgt fa fa-refresh " type="button" onclick="clearAll();"></button>
                    </div>





                </div>

            </div>


            <div class="panel-body" id="gridcontent">
                @{Html.RenderAction("List", "LedgerGroup");}
            </div>
        </div>
    </div>
</div>

InventoryManagement/Areas/Masters/Views/LedgerGroup/List.cshtml
@model List<ViewModel.Common.List_Common>
@{
    var grid = new WebGrid(Model, canPage: true, canSort: false, rowsPerPage: 20, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridcontent");
    grid.Pager(WebGridPagerModes.All);
    int i = 1;
}



    
            @grid.GetHtml(tableStyle: "table  table-responsive table-striped table-bordered table-hover topmrgn5px",
        columns: grid.Columns(
                 grid.Column(header: "S.No #", format: (item) => new HtmlString(string.Format("<span>" + i++ + "</span> <input type=hidden value= " + item.Id + ">"))),  
        grid.Column("Name", "Name"),
        grid.Column("Alias_Name", "Alias Name"),
        grid.Column("Remarks", "Remarks"),
        grid.Column("Under_Name", "Under")
        //grid.Column(header: "Action", format: (item) => new HtmlString(

        //                        @Ajax.ActionLink(" ", "Create", "LedgerGroup", new { area = "Masters", Id = item.Id }, new AjaxOptions
        //                             {

        //                                 Confirm = "Are you sure to delete?",
        //                                 UpdateTargetId = "PageContent",
        //                                 HttpMethod = "GET",
        //                                 InsertionMode = InsertionMode.Replace,
        //                             }, new { @Class = "btn btn-default fa fa-pencil", @title = "Edit" }).ToString()
        //                             //+
        //                             //                   @Ajax.ActionLink(" ", "Delete", "LedgerGroup", new { area = "Masters", item.Id }, new AjaxOptions
        //                             //{
        //                            // Confirm = "Are you sure to delete?",
        //                             //    UpdateTargetId = "PageContent",
        //                             //    HttpMethod = "GET",
        //                             //    InsertionMode = InsertionMode.Replace,
        //                             //}, new { @Class = "btn btn-default fa fa-trash-o", @title = "Delete" }).ToString()
        //    ))
                
        ))

            @*<table class="table  table-responsive table-striped table-bordered table-hover topmrgn5px">
                    <tr>
                        <td>
                            Ledger Name
                        </td>
                        <td>
                            Alias Name
                        </td>
                        <td>
                            Remarks
                        </td>
                        <td>
                            Under Group
                        </td>

                        <td colspan="2">Action</td>
                    </tr>
                    @if (Model.Count != 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(x => item.Name)

                                </td>
                                <td>
                                    @Html.DisplayFor(x => item.Alias_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(x => item.Remarks)
                                </td>
                                <td>
                                    @Html.DisplayFor(x => item.Under_Name)
                                </td>

                                <td>
                                    @Ajax.ActionLink(" ", "Create", "Ledger", new { area = "Masters", Id = item.Id }, new AjaxOptions
                                    {

                                        UpdateTargetId = "PageContent",
                                        HttpMethod = "GET",
                                        InsertionMode = InsertionMode.Replace,
                                    }, new { @Class = "fa fa-pencil", })
                                </td>
                                <td>
                                    @Ajax.ActionLink(" ", "Create", "Ledger", new { area = "Masters", item.Id }, new AjaxOptions
                                    {

                                        UpdateTargetId = "PageContent",
                                        HttpMethod = "GET",
                                        InsertionMode = InsertionMode.Replace,
                                    }, new { @Class = "fa fa-trash-o", })
                                </td>
                            </tr>
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="4">
                                No Records found..
                            </td>
                        </tr>
                    }


                </table>*@

