InventoryManagement/Areas/Transactions/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ServiceLayer.Transactions;
using HotelManagementErp_Main.Helper;
using ViewModel.Transactions;
using System.Net;
using Newtonsoft.Json;
namespace InventoryManagement.Areas.Transactions.Controllers
{

    public class PaymentController : InventoryBaseController
    {
        //
        // GET: /Transactions/Payment/
        PaymentServiceLayer _db;
        
        public ActionResult Index()

        {

            //ViewBag.Tag = Tag;
         
            return View();
        }
        public ActionResult List( string search = "")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo ;
            _db = new PaymentServiceLayer(_dashboardData);
            
            var lst = _db.List(search);
            return View(lst);
        }
        public ActionResult Create(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
             PaymentInfo modelPayment;
            // ViewBag.Tag = Tag;
             //var lst = new ServiceLayer.AccountMaster.CustomerServicesLayer(_dashboardData.DbConnectionString).DDLBind(Tag, "").ToList();
            if (Id != 0)
            {
                modelPayment = _db.Find(Id);

                //  ModelPurMaster.ItemDetails.Add(new Purchase_Tra());

            }
            else
            {
                modelPayment = new PaymentInfo();
                modelPayment.VC_No = _db.GEN_VC_NO();
                modelPayment.Payment_Date = DateTime.Today;
                //modelPayment.Tag_Type = Tag;
            }
           // modelPayment.User_List = lst;
            BindDDL(modelPayment);
            return View(modelPayment);
        }
        [HttpPost]
        public ActionResult Create(PaymentInfo modelPayment)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = modelPayment.Tag_Type;
            if (ModelState.IsValid == true|| ModelState.IsValid==false)
            {
                if (modelPayment.Id != 0)
                {
                    _db.Update(modelPayment);
                }
                else
                {
                    _db.Create(modelPayment);

                }

                var lst = _db.List(modelPayment.Tag_Type);

                return View("List", lst);
            }
            return View(modelPayment);
        }
        public ActionResult GetBalance(int UserId)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            var bal = _db.GetBalance(UserId);
            return Json(bal, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult ViewPayment(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            PaymentInfo modelPayment;


            if (Id != 0)
            {
                modelPayment = _db.Find(Id);
                //modelReceiptNote = new ReceiptNoteInfo();

            }
            else
            {
                modelPayment = new PaymentInfo();
                modelPayment.Payment_Date = DateTime.Now;

              

              //  modelPayment.Receipt_Note_No = _db.GEN_ReceiptNo();

            }

            return PartialView(modelPayment);
        }
        public ActionResult GetChequeDetails(int Id=0,string Cheque_No="")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            var bal = _db.GetChequeDetails(Id,Cheque_No);
            return Json(!bal, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PaymentDetails(int UserId=0,string Tag="")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            var lst = _db.PaymentDetails(UserId, Tag);
            return View(lst);
        }
        public ActionResult BillDetails(int UserId = 0, string Tag = "")
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            var lst = _db.BillDetails(UserId, Tag);
            return View(lst);
        }
        public ActionResult PendingBillList(int UserId = 0,int Id=0)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);
            PaymentInfo modelPayment = new PaymentInfo();
            if (UserId > 0)
            {
                modelPayment.BillList = _db.PendingBillList(UserId,Id);
            }
            return View(modelPayment);
            //return Json(lst, JsonRequestBehavior.AllowGet);
        }
        private void BindDDL(PaymentInfo modelPayment)
        {
            var _dashboardData = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new PaymentServiceLayer(_dashboardData);


            modelPayment.User_List = _db.DDLBind("Supplier", "");
            modelPayment.LedgerList = _db.DDLBind("ALL", "");
            //modelPayment.Bill_List = _db.PendingBillList(modelPayment.User_Id);
            modelPayment.BillList = new List<BillList>();
           
        }
        }
    }


InventoryManagement/Areas/Transactions/Controllers/ReceiptController.cs
using HotelManagementErp_Main.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.Transactions;
using ServiceLayer.Transactions;
namespace InventoryManagement.Areas.Transactions.Controllers
{
    public class ReceiptController : InventoryBaseController
    {
        //
        // GET: /Transactions/Receipt/
        ReceiptServiceLayer _db;
        public ActionResult Index(string Tag = "")
        {
            int Val = Convert.ToInt32(TempData["SaveStatus"]);
            if (Val != null && Val != 0)
            {
                ViewBag.SaveStatus = Val;
            }
            ViewBag.Tag = Tag;
            return View();
        }
        public ActionResult List(string Tag = "", string search = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            var lst = _db.List(Tag);
            return View(lst);
        }
        public ActionResult Create(string Tag = "", int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ReceiptInfo modelReceipt;
            ViewBag.Tag = Tag;

            if (Id != 0)
            {
                modelReceipt = _db.Find(Id);



            }
            else
            {
                modelReceipt = new ReceiptInfo();
                modelReceipt.Receipt_Date = DateTime.Today;
                modelReceipt.Tag_Type = Tag;
                modelReceipt.VC_No = _db.GEN_VC_NO();
            }

            BindDDL(modelReceipt);
            return View(modelReceipt);
        }
        [HttpPost]
        public ActionResult Create(ReceiptInfo modelReceipt)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ViewBag.Tag = modelReceipt.Tag_Type;
            //  if (ModelState.IsValid == true || ModelState.IsValid == false)
            if (ModelState.IsValid)
            {
                if (modelReceipt.Id != 0)
                {
                    // _db.Update(modelReceipt);
                    TempData["SaveStatus"] = 2;
                }
                else
                {
                    // _db.Create(modelReceipt);
                    TempData["SaveStatus"] = 1;
                }

                // var lst = _db.List(modelReceipt.Tag_Type);

                // return View("List", lst);
                return RedirectToAction("Index");
            }
            BindDDL(modelReceipt);
            return View(modelReceipt);
        }
        public ActionResult GetBalance(int UserId)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            var bal = _db.GetBalance(UserId);
            return Json(bal, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult ViewReceipt(int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ReceiptInfo modelReceipt;


            if (Id >= 0)
            {
                modelReceipt = _db.Find(Id);
                //modelReceiptNote = new ReceiptNoteInfo();

            }
            else
            {
                modelReceipt = new ReceiptInfo();
                modelReceipt.Receipt_Date = DateTime.Now;



                //  modelPayment.Receipt_Note_No = _db.GEN_ReceiptNo();

            }

            return PartialView(modelReceipt);
        }
        public ActionResult GetChequeDetails(int Id = 0, string Cheque_No = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            var bal = _db.GetChequeDetails(Id, Cheque_No);
            return Json(!bal, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ReceiptDetails(int UserId = 0, string Tag = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            //  List<ReceiptDetails> lst = new List<ViewModel.Transactions.ReceiptDetails>();
            ViewBag.Tag = Tag;
            var lst = _db.ReceiptDetails(UserId, Tag).Take(10).ToList();
            return View(lst);
        }
        public ActionResult BillDetails(int UserId = 0, string Tag = "")
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ViewBag.Tag = Tag;
            //var lst = _db.BillDetails(UserId, Tag);
            return View();
        }
        public ActionResult PendingBillList(int UserId = 0, int Id = 0)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);
            ReceiptInfo modelReceipt = new ReceiptInfo();
            if (UserId > 0)
            {
                modelReceipt.BillList = _db.PendingBillList(UserId, Id);
            }
            return View(modelReceipt);
            //return Json(lst, JsonRequestBehavior.AllowGet);
        }
        private void BindDDL(ReceiptInfo modelReceipt)
        {
            var _dashboardData = ViewBag.UserLog;
            _db = new ReceiptServiceLayer(_dashboardData);


            modelReceipt.User_List = _db.DDLBind("Customer", "");
            modelReceipt.LedgerList = _db.DDLBind("ALL", "");
            //modelPayment.Bill_List = _db.PendingBillList(modelPayment.User_Id);
            modelReceipt.BillList = new List<BillList>();

        }
    }
}

InventoryManagement/Areas/Transactions/Views/Receipt/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = ViewBag.layout;
}

@*<script>
        $(function () {
            ApplyFilterOnTable();
        });
    </script>*@


<script>
    $(document).ready(function () {
        if ('@ViewBag.SaveStatus' == 1)
            toastr.success('Record successfully Saved');

        else if ('@ViewBag.SaveStatus' == 2)
            toastr.success('Record updated successfully');
    });
</script><div id="body" class="row">

    <div id="content">
        @{Html.RenderAction("List", "Receipt", new { Tag = @ViewBag.Tag });}
    </div>
</div>

InventoryManagement/Areas/Transactions/Views/Receipt/List.cshtml
@model List<ViewModel.Transactions.ReceiptInfo>
@{
    var grid = new WebGrid(Model, canPage: true, canSort: true, rowsPerPage: 20,
    selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
    grid.Pager(WebGridPagerModes.All);
    int row = 0;
}

<div class="panel">

    <div class="panel-heading  bg-margenta">

        <div class="row">

            <div class="col-md-9">
                <span>@ViewBag.Tag &nbsp;&nbsp; Receipt List</span>
            </div>

            <div class="col-md-3">
                @Ajax.ActionLink("New", "Create", "Receipt", new { area = "Transactions", Tag = ViewBag.Tag, Id = 0 }, new AjaxOptions
                            {
                                LoadingElementId = "Loader",
                                UpdateTargetId = "PageContent",
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                            }, new { @Class = "btn btn-default btn-xs btn-flat hgt", })

                <div class="btn-wrp"><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Import <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#">One</a></li><li><a href="#">Two</a></li><li><a href="#">Three</a></li></ul></div><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Export <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'csv', escape: 'false' });">CSV</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'excel', escape: 'false' });">EXCEL</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'doc', escape: 'false' });">DOC</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'pdf', escape: 'false' });">PDF</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'xml', escape: 'false' });">XML</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'sql', escape: 'false' });">SQL Script</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'json', escape: 'false' });">JSON</a></li></ul></div></div>
                <input type="text" placeholder="Search Here" class="hgt" />

            </div>





        </div>

    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-8" id="gridcontent" style="min-height:450px;border:solid silver 1px;">
                @grid.GetHtml(tableStyle: "gTable table table-responsive",

             columns: grid.Columns(
             grid.Column("S.No", format: item => item.WebGrid.Rows.IndexOf(item) + 1),

                                                 grid.Column("Date", format: (item) => item.Receipt_Date.ToString("dd-MM-yyyy")),
                                                 grid.Column(columnName: "VC_No", header: "Bill No", format: @<text> <input type="hidden" id="Id" name="Id" value='@item.Id' />@item.VC_No</text>),
             //grid.Column("Name", "Supplier Name"),
             //grid.Column("Address", "Address"),
             //grid.Column("Contact_No", "Contact No"),
                             //grid.Column("Email_Id", "Email Id"),
             //    grid.Column(columnName: "Amount", header: "Amount", format: @<i class="fa fa-rupee">&nbsp;&nbsp;@item.Amount</i>),
                       grid.Column(columnName: "Amount", header: "Amount", format: @<i class="fa fa-rupee">&nbsp;&nbsp; @item.Amount.ToString("#." + new string('0', 2))</i>),

                             grid.Column(header: "Action", format: (item) => new HtmlString(

                                                          @Ajax.ActionLink(" ", "Create", "Receipt", new { area = "Transactions", Tag = "CUSTOMER", Id = item.Id, }, new AjaxOptions
                                          {
                                             LoadingElementId="Loader",
                                              UpdateTargetId = "PageContent",
                                              HttpMethod = "GET",
                                              InsertionMode = InsertionMode.Replace,
                                          }, new { @Class = "btn btn-default fa fa-pencil", }).ToString()
                                          ))

                       //                         @Ajax.ActionLink("Payment Details", "PaymentDetails", "Payment", new { area = "Transactions", UserId = item.Id, Tag = "SUPPLIER" }, new AjaxOptions
                        //                         {

                       //                             UpdateTargetId = "PageContent",
                        //                             HttpMethod = "GET",
                        //                             InsertionMode = InsertionMode.Replace,
                        //                         }, new { @Class = "btn btn-xs  btn-default pull-left btn-flat", }).ToString()

                       //                   ))


                       )
                      )
            </div>
            <div class="col-md-4" id="ViewReceipt">

                @{Html.RenderAction("ViewReceipt", "Receipt", new { @area = "Transactions", Id = -1 });}


            </div>
        </div>

    </div>

</div>



<script>

    $('table tbody tr').click(function () {

        var selectedId = $(this).find("input[type='hidden']").val();


        $.ajax({
            url: '@Url.Action("ViewReceipt", "Receipt")',
            data: { 'Id': selectedId },
            type: "get",
            cache: false,
            success: function (savingStatus) {

                $('#ViewReceipt').html(savingStatus);

            },
            error: function (xhr, ajaxOptions, thrownError) {

            }
        });
    });
</script>
<style>
    .gTable tr:hover {
        background-color: skyblue;
    }
    /*.gTable tr:nth-child(1) {
        text-align: left;

    }*/

    .gTable tr :nth-child(4) {
        text-align: right;
    }

    .amount {
        text-align: right;
    }
</style>






InventoryManagement/Areas/Transactions/Views/Receipt/ReceiptDetails.cshtml
@model List<ViewModel.Transactions.ReceiptDetails>
@*@Html.ActionLink("Back", "Index", "Payment", new { Tag = ViewBag.Tag }, new { @class = "fa fa-arrow-circle-left btn btn-danger" })*@

<table class="table table-striped table-bordered table-hover table-responsive topmrgn5px" id="example">
    <tr>
        <td>
            Date
        </td>
        <td>
            Mode
        </td>

        <td>Amount</td>
        @*<td>Tax Amt.</td>
        <td>Bal. Amt</td>*@
        @*<td>
                Action
            </td>*@

    </tr>
    @if (Model.Count != 0)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.Receipt_Date)

                </td>
                <td>
                    @Html.DisplayFor(x => item.Receipt_Type)
                </td>


                <td align="right">
                    @Html.DisplayFor(x => item.Amount)
                </td>

                @*<td align="right">
                    @Html.DisplayFor(x => item.Tax_Amount)
                </td>

                <td align="right">
                    @Html.DisplayFor(x => item.Balance_Amount)
                </td>*@

                @*<td>
                        @Ajax.ActionLink("Edit", "Create", "Payment", new { area = "Transactions", Tag = item.Tag_Type, Id = item.Id }, new AjaxOptions
                                {
                                    LoadingElementId = "Loader",
                                    UpdateTargetId = "PageContent",
                                    HttpMethod = "GET",
                                    InsertionMode = InsertionMode.Replace,
                                }, new { @Class = "btn btn-xs  btn-default pull-left btn-flat", })


                    </td>*@
            </tr>
        }

    }
    else
    {
        <tr>
            <td colspan="5">
                No Records found..
            </td>
        </tr>
    }


</table>

InventoryManagement/Areas/Transactions/Views/Receipt/ViewReceipt.cshtml
@model ViewModel.Transactions.ReceiptInfo
@{


    string src = null;
    if (Model.Image_Path != null)
    {
        src = Model.Image_Path;
    }
    else
    {
        src = "/Themes/img/demo_img.gif";
    }

}

<div>




    <div class="panel panel-danger managepnl">

        <div class="panel-heading" style="background-color: #C4538A;color:white"><span>View Details</span> </div>


        <div class="panel-body">

            <div class="row">
                <div class="col-md-4">
                    <div id="imgTest">
                        <img src="@src" class="img-responsive img-thumbnail mangaeimg" />
                    </div>
                </div>
                <div class="col-md-8">
                    <table class="table table-responsive topmrgn5px">
                        <tr>
                            <td>
                                @Html.Label("Code")

                                @Html.HiddenFor(x => x.Id)

                            </td>
                            <td>

                                <span>@Model.Code</span>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                @Html.Label("Supplier Name")
                            </td>
                            <td>
                                <span>@Model.Name</span>
                            </td>
                        </tr>



                        <tr>
                            <td>
                                @Html.Label("Contact No")
                            </td>
                            <td>
                                <span>@Model.Contact_No</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.Label("Email")
                            </td>
                            <td>
                                <span>@Model.Email</span>
                            </td>
                        </tr>




                    </table>
                </div>
            </div>

            <table class="table table-responsive  topmrgn5px">




                <tr>
                    <td>
                        @Html.Label("Remarks")
                    </td>
                    <td>
                        <span>@Model.Remarks</span>
                    </td>
                </tr>
            </table>

            <hr style="border:solid silver 1px;" />
            <div align="center"><h4><label>Receipt Details</label></h4></div>
            @{
                Html.RenderAction("ReceiptDetails", "Receipt", new { UserId = Model.User_Id, Tag = "Customer" });
            }
        </div>

    </div>

</div>