InventoryManagement/Areas/Masters/Controllers/TaxController.cs
using HotelManagementErp_Main.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.Common;
using ServiceLayer.Masters;
namespace InventoryManagement.Areas.Masters.Controllers
{
    public class TaxController : InventoryBaseController
    {
        //
        // GET: /Masters/TaxMaster/
        TaxServiceLayer _db;
        public ActionResult Index()
        {
            int val = Convert.ToInt32(TempData["SavedStatus"]);
            if (val != null && val != 0)
            {
                ViewBag.SaveStatus = val;
            }
            return View();
        }
        public ActionResult List(string Search = "")
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);
            var lst = _db.List(Search);
            return View(lst);
        }
        public ActionResult Create(int Id = 0)
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);
            Tax tax;
            if (Id != 0)
            {
                tax = _db.Find(Id);
            }
            else
            {
                tax = new Tax();
                tax.Code = _db.GEN_TaxCode();
            }
            return View(tax);
        }
        [HttpPost]
        public ActionResult Create(Tax modeltax)
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);
            var Status = false;
            if (ModelState.IsValid || ModelState.IsValid == false)
            {
                if (modeltax.Id != 0)
                {
                    Status = _db.Update(modeltax);
                    TempData["SavedStatus"] = 2;
                }
                else
                {

                    Status = _db.Create(modeltax);
                    TempData["SavedStatus"] = 1;
                }
                if (Status)
                    return View("Index");
                else
                    return View(modeltax);
            }
            return View(modeltax);
        }
        public ActionResult GetTaxRate(int Id = 0)
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);
            var result = 0.0m;
            if (Id != 0)
            {
                var tax = _db.Find(Id);
                result = tax != null ? tax.Rate : 0.00m;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int Id = 0)
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);
            bool result = false;
            if (Id > 0)
            {
                result = _db.Delete(Id);
            }
            var lst = _db.List();
            return PartialView("List", lst);
        }
        public ActionResult IsNameExists(int Id, string Name)
        {
            var info = ViewBag.UserLog as ViewModel.Users.LoginInfo;
            _db = new TaxServiceLayer(info);

            return Json(!_db.IsNameExists(Id, Name), JsonRequestBehavior.AllowGet);
        }
    }
}

InventoryManagement/Areas/Transactions/Controllers/StockMasterController.cs
using HotelManagementErp_Main.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceLayer.Transactions;
using ViewModel.Transactions;
namespace InventoryManagement.Areas.Transactions.Controllers
{
    public class StockMasterController : InventoryBaseController
    {
        //
        // GET: /Transactions/StockMaster/
        StockMasterServiceLayer _db;
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string search="")
        {
            logger.Info("Stock Master Index Page Debugging Started");
            var _dashboardData = ViewBag.UserLog;
            _db = new StockMasterServiceLayer(_dashboardData);
            // List<ViewModel.Transactions.StockMaster> lst = new List<ViewModel.Transactions.StockMaster>();
            var lst = _db.List(search);

            return View(lst);
        }
        public ActionResult ItemAvailabltyDetails(int ItemId = 0)
        {
            logger.Info("Stock Master Index Page Debugging Started");
            var _dashboardData = ViewBag.UserLog;
            _db = new StockMasterServiceLayer(_dashboardData);
            var data = _db.Find(ItemId);

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult MasterDetails(int ItemId = 0)
        {
            logger.Info("Stock Master Index Page Debugging Started");
            var _dashboardData = ViewBag.UserLog;
            _db = new StockMasterServiceLayer(_dashboardData);
            // var data = _db.Find(ItemId);
            MasterDetailsInfo modelMasterDetail = new MasterDetailsInfo();
            return View(modelMasterDetail);
        }

        public ActionResult ViewStockMasterdetail(long Id)
        {
            logger.Info("Stock Master Index Page Debugging Started");
            var _dashboardData = ViewBag.UserLog;
            _db = new StockMasterServiceLayer(_dashboardData);
            List<StockMasterDetail> stockMstDetails = new List<StockMasterDetail>();
            StockMaster StockMst = new StockMaster();
            //if (Id > 0)
            //{
            var stockMst1 = _db.FindStockMaster(Id);
            StockMst.StockMstDetails = stockMst1;
            //DdlBind(stock);
            // }
            return View(StockMst);
        }
        public ActionResult ViewStockMasterItemdetail(long Id)
        {
            logger.Info("Stock Master Index Page Debugging Started");
            var _dashboardData = ViewBag.UserLog;
            _db = new StockMasterServiceLayer(_dashboardData);
            List<StockMasterDetail> stockMstDetails = new List<StockMasterDetail>();
            StockMaster StockMst = new StockMaster();
            //if (Id > 0)
            //{
            var stockMst1 = _db.FindStockMaster(Id);
            StockMst.StockMstDetails = stockMst1;
            //DdlBind(stock);
            // }
            return View(StockMst);

        }
    }
}

InventoryManagement/Areas/Transactions/Views/StockMaster/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = ViewBag.layout;
}


        @{Html.RenderAction("List", "StockMaster");}

InventoryManagement/Areas/Transactions/Views/StockMaster/List.cshtml
@model List<ViewModel.Transactions.StockMaster>
@{
    var grid = new WebGrid(Model, canPage: true, canSort: true, selectionFieldName: "selectedRow", rowsPerPage: 20, ajaxUpdateContainerId: "PageContent");
    grid.Pager(WebGridPagerModes.All);
}
<script>
    $(document).ready(function () {
        $('#searchText').click(function () {

            var data = $('#SearchText').val();
            if (data != null)
                FilterData(data, '@Url.Action("List", "StockMaster", new { area = "Transactions" })', '#PageContent');
        });

    });
</script>

<script type="text/javascript">
    $(function () {
        if ($('#spStatus').text() == 'In-Stock') {
            $('#spStatus').css('color', 'green');
        }
        else {
            $('#spStatus').css('color', 'red');
        }

    });
</script>

<div class="panel">

    <div class="panel-heading  bg-margenta">
        <div class="row">

            <div class="col-md-9">
                <i class="fa fa-list"></i>
                <span>Stock Master</span>


            </div>

            <div class="col-md-3">
                @*@Ajax.ActionLink("New", "Create", "Tax", new { area = "Masters", Id = 0 }, new AjaxOptions
                    {

                        UpdateTargetId = "PageContent",
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                    }, new { @Class = "btn btn-default btn-xs btn-flat hgt", })*@


                <div class="btn-wrp"><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Import <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#">One</a></li><li><a href="#">Two</a></li><li><a href="#">Three</a></li></ul></div><div class="dropdown"><button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Export <span class="caret"></span></button><ul class="dropdown-menu"><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'csv', escape: 'false' });">CSV</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'excel', escape: 'false' });">EXCEL</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'doc', escape: 'false' });">DOC</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'pdf', escape: 'false' });">PDF</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'xml', escape: 'false' });">XML</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'sql', escape: 'false' });">SQL Script</a></li><li><a href="#" onclick="$('#gridcontent table').tableExport({ type: 'json', escape: 'false' });">JSON</a></li></ul></div></div>
                <input type="text" placeholder="Search Challan Number " class="" id="SearchText" />
                <button class="btn btn-default btn-xs btn-flat hgt fa fa-search" id="searchText" type="button"></button>
                <button class="btn btn-default btn-xs btn-flat hgt fa fa-refresh " type="button" onclick="clearAll();"></button>>
            </div>





        </div>

    </div>


    <div class="panel-body" id="gridcontent">
        <div class="row">
            <div class="col-md-9">
                @grid.GetHtml(tableStyle: "table table-striped table-bordered table-hover table-responsive topmrgn5px",
                    columns: grid.Columns(
                        //grid.Column("Item_Code", "Code"),
            grid.Column("Name", "Name"),
                        //  grid.Column("Alias_Name", "Alias Name"),
             grid.Column("GroupName", "Group Name"),
            grid.Column("CategoryName", "Category Name"),
            grid.Column("Qty", "Quantity"),
                                       grid.Column("UnitName", "Unit Name")
                        //  grid.Column("Rate", "Purchase Rate")


        ))





            </div>
            <div class="col-md-3">
                <div class="panel panel-info">
                    <div class="panel-heading bg-aqua">
                        <span>View Details</span>
                    </div>
                    <div class="panel-body" style="border:silver 1px;">
                        @***************commeneted by anurag*************@
                        @*<table class="table table-bordered table-striped">
                                <tr><td colspan="2"><label>Stock Master Details</label></td></tr>
                                <tr><td>Today Total Sales</td><td><span id="Customer_Code">17</span></td></tr>
                                <tr><td>Today Total Purchase</td><td><span id="Pending_Order">32</span></td></tr>
                                <tr><td>Take Quation</td><td><span id="Due_Amount"> 19</span></td></tr>
                                <tr><td>Give</td><td><span id="Bal_Amount">36</span></td></tr>


                            </table>*@

                        @*<table class="table table-bordered table-striped">

                                <tr><td colspan="2"><label>Item Details</label></td></tr>
                                <tr>  <td><span>Item Code</span></td><td><span id="StockDetails_Item_Code">101</span></td> </tr>
                                <tr>  <td><span>Min Qty</span></td><td><span id="StockDetails_Item_Date"> 20</span></td> </tr>
                                <tr>  <td><span>Avialable Qty</span></td><td><span id="StockDetails_Available_Qty"> 50</span></td> </tr>
                                <tr>  <td><span>Status</span></td><td><span id="StockDetails_Min_Qty">In Stock</span></td> </tr>

                            </table>*****************till Here*********************@
                        @***************already commented*****************@
                        @*@if (Model.StockDetails.Image_Url != null)
                            {
                                <img src="@Model.StockDetails.Image_Url" class="img-responsive" style="max-height:120px;min-height:120px;" />
                            }
                            else
                            {
                                <img src="~/Themes/img/avatar5.png" class="img-responsive" style="max-height:120px;min-height:120px;" />
                            }*@

                        <div class="table table-bordered table-striped" id="ViewStock">
                            @{Html.RenderAction("ViewStockMasterdetail", "StockMaster", new { Id = -1 });}
                        </div>
                        <div class="table table-bordered table-striped" id="ViewStock">
                            @{Html.RenderAction("ViewStockMasterItemdetail", "StockMaster", new { Id = -1 });}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

InventoryManagement/Areas/Transactions/Views/StockMaster/MasterDetails.cshtml
@model ViewModel.Transactions.MasterDetailsInfo
<div class="panel">

    <div class="panel-heading bg-aqua">
        <span>View Details</span>
    </div>

    <div class="panel-body" style="border:silver 1px;">

        <table class="table table-bordered table-striped">
            <tr><td colspan="2"><label>Customer Details</label></td></tr>
            <tr><td>Customer Code</td><td><span id="Customer_Code">@Html.DisplayFor(x => x.Customer_Code)</span></td></tr>
            <tr><td>Pending Order</td><td><span id="Pending_Order"> @Html.DisplayFor(x => x.Pending_Order)</span></td></tr>
            <tr><td>Due Amount</td><td><span id="Due_Amount"> @Html.DisplayFor(x => x.Due_Amount)</span></td></tr>
            <tr><td>Balance Amount</td><td><span id="Bal_Amount"> @Html.DisplayFor(x => x.Bal_Amount)</span></td></tr>
           
           
        </table>

        <table class="table table-bordered table-striped">

            <tr><td colspan="2"><label>Availablity</label></td></tr>
            <tr>  <td><span>Item Code</span></td><td><span id="StockDetails_Item_Code"> @Html.DisplayFor(x => x.StockDetails.Item_Code)</span></td> </tr>
            <tr>  <td><span>Shipment  Date</span></td><td><span id="StockDetails_Item_Date"> 11/04/2016</span></td> </tr>
            <tr>  <td><span>Item Availablity</span></td><td><span id="StockDetails_Available_Qty"> @Html.DisplayFor(x => x.StockDetails.Available_Qty)</span></td> </tr>
            <tr>  <td><span>Min Qty Alert</span></td><td><span id="StockDetails_Min_Qty"> @Html.DisplayFor(x => x.StockDetails.Min_Qty)</span></td> </tr>
            <tr>  <td><span>Purchasing Rate</span></td><td><span id="StockDetails_Purchase_Rate"> @Html.DisplayFor(x => x.StockDetails.Purchase_Rate)</span></td> </tr>
            <tr>  <td><span>Selling Rate</span></td><td><span id="StockDetails_Selling_Rate"> @Html.DisplayFor(x => x.StockDetails.Selling_Rate)</span></td> </tr>
        </table>
        @if (Model.StockDetails.Image_Url != null) { 
        <img src="@Model.StockDetails.Image_Url" class="img-responsive" style="max-height:120px;min-height:120px;" />
        }
        else
        {
        <img src="~/Themes/img/avatar5.png" class="img-responsive" style="max-height:120px;min-height:120px;" />    
        }

    </div>

</div>

InventoryManagement/Areas/Transactions/Views/StockMaster/ViewStockMasterItemdetail.cshtml
@model ViewModel.Transactions.StockMaster
@*<div class="panel panel-danger" style="min-height:450px;">

    <div class="panel-heading" style="background-color: #C4538A;color:white"><span>View Details</span> </div>


     <div class="panel-body">*@

@*<div>
        <div id="imgTest">
            <img src="@src" class="img-responsive img-thumbnail" style="max-height:120px;min-height:120px;max-width:120px;min-width:120px;" />
        </div>
    </div>*@
<table class="table table-bordered table-striped">
    <tr><td colspan="2"><label>Item Details</label></td></tr>
    <tr>
        <td>
            @Html.Label("Item Code")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "ITEMCODE").Description</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Item Name")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "ITEMNAME").Description</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Total Purchase")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "TOTALPURCHASE").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Total Sales")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "TOTALSALES").Value</span>
        </td>
    </tr>

    <tr>
        <td>
            @Html.Label("Min Qty")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "MINIMUMQUANTITY").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Available Qty")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "AVAILABLEQUANTITY").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Opening Qty")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "OPENINGQUANTITY").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Purchase Return")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "PURCHASERETURN").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Sales Return")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "SALESRETURN").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Status")
        </td>
        <td>
            <span id="spStatus">@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "STATUS").Description</span>
        </td>
    </tr>
</table>
@*</div>
    </div>*@

InventoryManagement/Areas/Transactions/Views/StockMaster/ViewStockMasterdetail.cshtml
@model ViewModel.Transactions.StockMaster
@{

    string src = null;
    if (Model.StockMstDetails.FirstOrDefault(x => x.TagName == "IMAGEURL").Description != null)
    {
         src = Model.StockMstDetails.FirstOrDefault(x => x.TagName == "IMAGEURL").Description;

      
    }
    else
    {
        src = "/Themes/img/demo_img.gif";
    }

}
@*<div class="panel panel-danger" style="min-height:450px;">*@

@*<div class="panel-heading" style="background-color: #C4538A;color:white"><span>View Details</span> </div>


    <div class="panel-body">*@

<div>
    <div id="imgTest">
        <img id="imgSrc" src="@src" class="img-responsive img-thumbnail" title="No Image" style="max-height:120px;min-height:120px;max-width:120px;min-width:120px;" />
    </div>
</div>
<table class="table table-bordered table-striped">
    <tr><td colspan="2"><label>Stock Master Details</label></td></tr>
    <tr>
        <td>
            @Html.Label("Today Total Sales")
            @*@Html.HiddenFor(x => x.Id)*@
        </td>
        <td>

            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "TODAYSALES").Value</span>
        </td>
    </tr>

    <tr>
        <td>
            @Html.Label("Today Total Purchase")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "TODAYPURCHASE").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Sales Quotations")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "SALESQUOTATION").Value</span>
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Purchase Quotations")
        </td>
        <td>
            <span>@Model.StockMstDetails.FirstOrDefault(x => x.TagName == "PURCHASEQUOTATION").Value</span>
        </td>
    </tr>
</table>
@*</div>
    </div>*@